//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sirensong.Localization.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Sirensong.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ContentDifficulty_Normal {
            get {
                return ResourceManager.GetString("ContentDifficulty_Normal", resourceCulture);
            }
        }
        
        internal static string ContentDifficulty_Hard {
            get {
                return ResourceManager.GetString("ContentDifficulty_Hard", resourceCulture);
            }
        }
        
        internal static string ContentDifficulty_Extreme {
            get {
                return ResourceManager.GetString("ContentDifficulty_Extreme", resourceCulture);
            }
        }
        
        internal static string ContentDifficulty_Savage {
            get {
                return ResourceManager.GetString("ContentDifficulty_Savage", resourceCulture);
            }
        }
        
        internal static string ContentDifficulty_Ultimate {
            get {
                return ResourceManager.GetString("ContentDifficulty_Ultimate", resourceCulture);
            }
        }
        
        internal static string ContentDifficulty_Unreal {
            get {
                return ResourceManager.GetString("ContentDifficulty_Unreal", resourceCulture);
            }
        }
        
        internal static string ContentType_AllianceRaid {
            get {
                return ResourceManager.GetString("ContentType_AllianceRaid", resourceCulture);
            }
        }
        
        internal static string ContentType_Unknown {
            get {
                return ResourceManager.GetString("ContentType_Unknown", resourceCulture);
            }
        }
        
        internal static string ContentType_Roulette {
            get {
                return ResourceManager.GetString("ContentType_Roulette", resourceCulture);
            }
        }
        
        internal static string ContentType_Dungeon {
            get {
                return ResourceManager.GetString("ContentType_Dungeon", resourceCulture);
            }
        }
        
        internal static string ContentType_Guildhest {
            get {
                return ResourceManager.GetString("ContentType_Guildhest", resourceCulture);
            }
        }
        
        internal static string ContentType_Trial {
            get {
                return ResourceManager.GetString("ContentType_Trial", resourceCulture);
            }
        }
        
        internal static string ContentType_Raid {
            get {
                return ResourceManager.GetString("ContentType_Raid", resourceCulture);
            }
        }
        
        internal static string ContentType_PvP {
            get {
                return ResourceManager.GetString("ContentType_PvP", resourceCulture);
            }
        }
        
        internal static string ContentType_QuestBattle {
            get {
                return ResourceManager.GetString("ContentType_QuestBattle", resourceCulture);
            }
        }
        
        internal static string ContentType_FATE {
            get {
                return ResourceManager.GetString("ContentType_FATE", resourceCulture);
            }
        }
        
        internal static string ContentType_TreasureHunt {
            get {
                return ResourceManager.GetString("ContentType_TreasureHunt", resourceCulture);
            }
        }
        
        internal static string ContentType_Levequest {
            get {
                return ResourceManager.GetString("ContentType_Levequest", resourceCulture);
            }
        }
        
        internal static string ContentType_GrandCompany {
            get {
                return ResourceManager.GetString("ContentType_GrandCompany", resourceCulture);
            }
        }
        
        internal static string ContentType_Companion {
            get {
                return ResourceManager.GetString("ContentType_Companion", resourceCulture);
            }
        }
        
        internal static string ContentType_TribalQuest {
            get {
                return ResourceManager.GetString("ContentType_TribalQuest", resourceCulture);
            }
        }
        
        internal static string ContentType_OverallCompletion {
            get {
                return ResourceManager.GetString("ContentType_OverallCompletion", resourceCulture);
            }
        }
        
        internal static string ContentType_PlayerCommendation {
            get {
                return ResourceManager.GetString("ContentType_PlayerCommendation", resourceCulture);
            }
        }
        
        internal static string ContentType_DiscipleOfTheLand {
            get {
                return ResourceManager.GetString("ContentType_DiscipleOfTheLand", resourceCulture);
            }
        }
        
        internal static string ContentType_DiscipleOfTheHand {
            get {
                return ResourceManager.GetString("ContentType_DiscipleOfTheHand", resourceCulture);
            }
        }
        
        internal static string ContentType_RetainerVenture {
            get {
                return ResourceManager.GetString("ContentType_RetainerVenture", resourceCulture);
            }
        }
        
        internal static string ContentType_GoldSaucer {
            get {
                return ResourceManager.GetString("ContentType_GoldSaucer", resourceCulture);
            }
        }
        
        internal static string ContentType_DeepDungeon {
            get {
                return ResourceManager.GetString("ContentType_DeepDungeon", resourceCulture);
            }
        }
        
        internal static string ContentType_WonderousTails {
            get {
                return ResourceManager.GetString("ContentType_WonderousTails", resourceCulture);
            }
        }
        
        internal static string ContentType_CustomDelivery {
            get {
                return ResourceManager.GetString("ContentType_CustomDelivery", resourceCulture);
            }
        }
        
        internal static string ContentType_Eureka {
            get {
                return ResourceManager.GetString("ContentType_Eureka", resourceCulture);
            }
        }
        
        internal static string ContentType_SouthernFront {
            get {
                return ResourceManager.GetString("ContentType_SouthernFront", resourceCulture);
            }
        }
        
        internal static string ContentType_VCDungeon {
            get {
                return ResourceManager.GetString("ContentType_VCDungeon", resourceCulture);
            }
        }
        
        internal static string ContentType_AllianceRaid_Plural {
            get {
                return ResourceManager.GetString("ContentType_AllianceRaid_Plural", resourceCulture);
            }
        }
        
        internal static string ContentType_Companion_Plural {
            get {
                return ResourceManager.GetString("ContentType_Companion_Plural", resourceCulture);
            }
        }
        
        internal static string ContentType_CustomDelivery_Plural {
            get {
                return ResourceManager.GetString("ContentType_CustomDelivery_Plural", resourceCulture);
            }
        }
        
        internal static string ContentType_DeepDungeon_Plural {
            get {
                return ResourceManager.GetString("ContentType_DeepDungeon_Plural", resourceCulture);
            }
        }
        
        internal static string ContentType_DiscipleOfTheHand_Plural {
            get {
                return ResourceManager.GetString("ContentType_DiscipleOfTheHand_Plural", resourceCulture);
            }
        }
        
        internal static string ContentType_DiscipleOfTheLand_Plural {
            get {
                return ResourceManager.GetString("ContentType_DiscipleOfTheLand_Plural", resourceCulture);
            }
        }
        
        internal static string ContentType_Dungeon_Plural {
            get {
                return ResourceManager.GetString("ContentType_Dungeon_Plural", resourceCulture);
            }
        }
        
        internal static string ContentType_Eureka_Plural {
            get {
                return ResourceManager.GetString("ContentType_Eureka_Plural", resourceCulture);
            }
        }
        
        internal static string ContentType_FATE_Plural {
            get {
                return ResourceManager.GetString("ContentType_FATE_Plural", resourceCulture);
            }
        }
        
        internal static string ContentType_GoldSaucer_Plural {
            get {
                return ResourceManager.GetString("ContentType_GoldSaucer_Plural", resourceCulture);
            }
        }
        
        internal static string ContentType_GrandCompany_Plural {
            get {
                return ResourceManager.GetString("ContentType_GrandCompany_Plural", resourceCulture);
            }
        }
        
        internal static string ContentType_Guildhest_Plural {
            get {
                return ResourceManager.GetString("ContentType_Guildhest_Plural", resourceCulture);
            }
        }
        
        internal static string ContentType_OverallCompletion_Plural {
            get {
                return ResourceManager.GetString("ContentType_OverallCompletion_Plural", resourceCulture);
            }
        }
        
        internal static string ContentType_PlayerCommendation_Plural {
            get {
                return ResourceManager.GetString("ContentType_PlayerCommendation_Plural", resourceCulture);
            }
        }
        
        internal static string ContentType_PvP_Plural {
            get {
                return ResourceManager.GetString("ContentType_PvP_Plural", resourceCulture);
            }
        }
        
        internal static string ContentType_QuestBattle_Plural {
            get {
                return ResourceManager.GetString("ContentType_QuestBattle_Plural", resourceCulture);
            }
        }
        
        internal static string ContentType_Raid_Plural {
            get {
                return ResourceManager.GetString("ContentType_Raid_Plural", resourceCulture);
            }
        }
        
        internal static string ContentType_RetainerVenture_Plural {
            get {
                return ResourceManager.GetString("ContentType_RetainerVenture_Plural", resourceCulture);
            }
        }
        
        internal static string ContentType_Roulette_Plural {
            get {
                return ResourceManager.GetString("ContentType_Roulette_Plural", resourceCulture);
            }
        }
        
        internal static string ContentType_SouthernFront_Plural {
            get {
                return ResourceManager.GetString("ContentType_SouthernFront_Plural", resourceCulture);
            }
        }
        
        internal static string ContentType_TreasureHunt_Plural {
            get {
                return ResourceManager.GetString("ContentType_TreasureHunt_Plural", resourceCulture);
            }
        }
        
        internal static string ContentType_Trial_Plural {
            get {
                return ResourceManager.GetString("ContentType_Trial_Plural", resourceCulture);
            }
        }
        
        internal static string ContentType_TribalQuest_Plural {
            get {
                return ResourceManager.GetString("ContentType_TribalQuest_Plural", resourceCulture);
            }
        }
        
        internal static string ContentType_Unknown_Plural {
            get {
                return ResourceManager.GetString("ContentType_Unknown_Plural", resourceCulture);
            }
        }
        
        internal static string ContentType_VCDungeon_Plural {
            get {
                return ResourceManager.GetString("ContentType_VCDungeon_Plural", resourceCulture);
            }
        }
        
        internal static string ContentType_WonderousTails_Plural {
            get {
                return ResourceManager.GetString("ContentType_WonderousTails_Plural", resourceCulture);
            }
        }
        
        internal static string ContentType_Levequest_Plural {
            get {
                return ResourceManager.GetString("ContentType_Levequest_Plural", resourceCulture);
            }
        }
    }
}
